version: '2'

services:
    mongodb:
        image: mongo
        volumes:
            - "./data:/data"
        ports:
            - "27017:27017"
        networks:
            - nodeapp-network
    neo4j:
        image: neo4j
        volumes: 
            - "./data:/data"
            - "./log:/log"
            - "./import:/import"
            - "./conf:/conf"
        ports:
            - "7474:7474"
            - "7473:7473"
            - "7687:7687"
        networks:
            - nodeapp-network
        # environment:
        #     - NEO4J_dbms_connector_https_advertised__address=localhost:7473 
        #     - NEO4J_dbms_connector_http_advertised__address=localhost:7474 
        #     - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
    redis:
        image: redis
        volumes:
            - "./data:/data"
        ports:
            - "6379:6379"
        networks:
            - nodeapp-network
 
    node:
        build: 
            context: .
            dockerfile: node.dockerfile
        ports:
            - "8080:8080"
        networks:
            - nodeapp-network
networks:
    nodeapp-network:
        driver: bridge 